### ISSUE TITLE
Complexity for Weapon Mods

### ISSUE THREAD

**Issue by Jackal97** [Muttley/foundryvtt-fallout#297] opened 2024-04-20 09:58 UTC
Wondering if there could be a box for complexity in the weapon mod item.
Maybe replace the rarity with complexity?

**Comment by Muttley** [comment] 2024-05-01 09:30
This should actually be part of a new Recipe item type which will allow you to craft the actual mods themselves.

Closing as duplicate of #135

**Closed by Muttley** 2024-05-01 09:30 UTC

**Comment by Jackal97** [comment] 2024-05-01 10:57
Awesome Thanks!
